project:
  type: website
  output-dir: _site

website:
  title: "ISSS626 Portfolio — HUANG PENGXIN"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Hands-on
        menu:
          - text: Ex01a · Geospatial Wrangling
            href: Hands-on_Ex/Hands-on_ex01/ex01a.qmd
          - text: Ex01b · Choropleth Mapping
            href: Hands-on_Ex/Hands-on_ex01/ex01b.qmd
          - text: Ex02a · Child Care Choropleth
            href: Hands-on_Ex/Hands-on_ex02/ex02a.qmd
          - text: Ex02b · Spatial Weights & Autocorrelation
            href: Hands-on_Ex/Hands-on_ex02/ex02b.qmd
          - text: Ex03a · ST Point Patterns
            href: Hands-on_Ex/Hands-on_ex03/ex03.qmd
          - text: Ex04 · Spatial Weights (Apps)
            href: Hands-on_Ex/Hands-on_ex04/ex04.qmd
          - text: Ex05a · Global Spatial Autocorr
            href: Hands-on_Ex/Hands-on_ex05/ex05a.qmd
          - text: Ex05b · Local Spatial Autocorr
            href: Hands-on_Ex/Hands-on_ex05/ex05b.qmd
          - text: Ex06 · Geospatial Analytics for Social Good
            href: Hands-on_Ex/Hands-on_ex06/ex06.qmd
          - text: Ex07 · Geographically Weighted Regression
            href: Hands-on_Ex/Hands-on_ex07/ex07.qmd
          - text: Ex08 · Geographically Weighted Prediction
            href: Hands-on_Ex/Hands-on_ex08/ex08.qmd
          - text: Ex09 · Spatial Accessibility (2SFCA/E2SFCA)
            href: Hands-on_Ex/Hands-on_ex09/ex09.qmd
      - text: In-class
        href: In-class_Ex/index.qmd
      - text: Take-home
        href: Take-home_Ex/index.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto

editor: visual
